script/get-ml-model-llama2/meta.yaml
script/get-ml-model-llama3/meta.yaml

In reference to issue: 
https://github.com/mlcommons/mlperf-automations/issues/236

Fix for issue #236

---

script/get-dataset-waymo-calibration/COPYRIGHT.md
script/get-dataset-waymo-calibration/customize.py
script/get-dataset-waymo-calibration/meta.yaml
script/get-dataset-waymo-calibration/run-rclone.sh

PR for documentation update is raised [here](https://github.com/mlcommons/inference/pull/2130)

Add script to download waymo calibration dataset

---

script/get-dataset-mlperf-inference-mixtral/meta.yaml

Reference: https://github.com/mlcommons/inference/tree/master/language/mixtral-8x7b#calibration-dataset

Updated mixtral dataset download based on latest inference readme

---

script/get-one-api/COPYRIGHT.md
script/get-one-api/customize.py
script/get-one-api/meta.yaml
script/get-one-api/run.bat
script/get-one-api/run.sh

in reference to issue: https://github.com/mlcommons/mlperf-automations/issues/291

Add get-oneapi compiler(WIP)

---

.github/workflows/test-mlc-script-pip.yml
setup.py

Add tests for mlc-scripts installation

---

script/generate-mlperf-inference-submission/meta.yaml

In reference to issue: https://github.com/mlcommons/mlperf-automations/issues/322

link submit-mlperf-results with generate-mlperf-inference-submission

---

script/generate-mlperf-inference-submission/customize.py

Currently the GitHub action for submission generation in inference repo is [failing](https://github.com/mlcommons/inference/actions/runs/14187789456/job/39746149242?pr=2162). It was not caught earlier as `continue-on-error` flag was set to `true`.

Handle submission base directory properly

---

script/get-dataset-waymo-calibration/meta.yaml
script/get-dataset-waymo/meta.yaml
script/get-rclone-config/customize.py
script/get-rclone-config/meta.yaml

In reference to issue: https://github.com/mlcommons/mlperf-automations/issues/372

Skip authentication when service account credentials are provided

---

.github/workflows/test-mlperf-inference-resnet50-closed-division.yml
script/app-mlperf-inference/customize.py

In reference to issue: https://github.com/mlcommons/mlperf-automations/issues/247
Failing GitHub actions: https://github.com/mlcommons/mlperf-automations/actions/runs/14150821438/job/39643726179

Path string fix

---

script/gemini_call/customize.py
script/gemini_call/gemini_call.py
script/gemini_call/meta.yaml
script/gemini_call/run.bat
script/gemini_call/run.sh

This PR is related to the PR: https://github.com/GATEOverflow/go-scripts/pull/12 and is used to send api calls to Gemini for all the questions. I have added more information here: https://github.com/GATEOverflow/go-scripts/pull/12

Contest 2025 gemini call

---

automation/script/module.py
script/get-git-repo/meta.yaml
script/set-cpu-frequency/run.sh

Support base variations inside combination of variations, fixes #38, support list in update_tags_from_env

---

script/get-gcc/customize.py

Fix gcc installed path

---

script/app-mlperf-inference-mlcommons-python/meta.yaml
script/app-mlperf-inference/meta.yaml

Migrate dataset and model downloads to R2

---

script/app-mlperf-inference-mlcommons-python/meta.yaml
script/app-mlperf-inference/meta.yaml
script/get-dataset-cnndm/meta.yaml

Modifications for llama3.1-8b edge

---

automation/script/help.py
automation/script/module.py

Add initial draft of help.py

---

automation/script/help.py
automation/script/module.py

Improve script help

---

script/app-mlperf-inference-mlcommons-python/meta.yaml
script/app-mlperf-inference/meta.yaml
script/download-and-extract/meta.yaml
script/download-file/meta.yaml
script/get-dataset-cnndm/meta.yaml
script/get-dataset-whisper/meta.yaml
script/get-ml-model-llama3/meta.yaml
script/get-ml-model-whisper/meta.yaml
script/get-preprocessed-dataset-mlperf-deepseek-r1/meta.yaml
script/get-python3/meta.yaml

Fixes for whisper, dont print python env at end

---

automation/script/module.py

Fix permission error for fake runs

---

automation/script/docker_utils.py

Fix default input keys in docker run command

---

automation/script/docker.py
script/app-mlperf-inference/meta.yaml
script/get-ml-model-gptj/meta.yaml
script/get-mlperf-inference-nvidia-common-code/meta.yaml
script/get-mlperf-inference-results/meta.yaml

Fix nvidia-mlperf-inference-v5.0-dev

Fix nvidia-mlperf-inference-v5.0-dev

---

automation/utils.py
script/get-generic-sys-util/meta.yaml
script/install-gcc-src/customize.py
script/install-gcc-src/meta.yaml
script/install-gcc-src/run.sh
script/install-llvm-src/customize.py
script/install-llvm-src/meta.yaml

Support env in os_info, cross-compilation for llvm

---

automation/script/help.py
automation/script/module.py
script/app-mlperf-inference-mlcommons-python/README.md
script/app-mlperf-inference-nvidia/README.md
script/app-mlperf-inference/README.md
script/build-mlperf-inference-server-nvidia/README.md
script/download-file/README.md
script/generate-mlperf-inference-submission/README.md
script/get-cache-dir/README.md
script/get-generic-sys-util/README.md
script/get-git-repo/README.md
script/get-ipol-src/meta.yaml
script/get-lib-jemalloc/README.md
script/get-lib-jemalloc/customize.py
script/get-lib-jemalloc/meta.yaml
script/get-ml-model-abtf-ssd-pytorch/README.md
script/get-ml-model-deeplabv3_plus/README.md
script/get-ml-model-resnet50/README.md
script/get-oneapi/README.md
script/get-spec-ptd/meta.yaml
script/get-tensorrt/meta.yaml
script/run-mlperf-inference-submission-checker/README.md
script/submit-mlperf-results/README.md

Merge from GO: fixes for --help

---

script/app-mlperf-inference-mlcommons-python/meta.yaml

Removed protobuf version requirement for mlperf-inference resnet50

---

.github/workflows/test-mlperf-inference-retinanet.yml

Potential fix for [https://github.com/mlcommons/mlperf-automations/security/code-scanning/12](https://github.com/mlcommons/mlperf-automations/security/code-scanning/12)
To fix this problem, we should prevent untrusted user-controlled input from being directly used in the shell context. The recommended approach is to pass the untrusted value (here, `github.event.pull_request.head.ref`) into an environment variable, and use the native shell environment variable syntax to reference it (`$BRANCH`). Specifically, for line 49: introduce an `env:` block to set the environment variable (for example, `BRANCH: ${{ github.event.pull_request.head.ref }}`), then reference it as `--branch="$BRANCH"` in the shell script. Similarly, consider also using `REPO: ${{ …

Potential fix for code scanning alert no. 12: Code injection

---

.github/workflows/run_tests_on_modified_meta_with_secrets.yml

Potential fix for [https://github.com/mlcommons/mlperf-automations/security/code-scanning/3](https://github.com/mlcommons/mlperf-automations/security/code-scanning/3)
To fix the problem, assign the untrusted input—`${{ github.event.pull_request.head.ref }}`—to an intermediate environment variable, then reference that environment variable in the shell command using native shell syntax (`$VAR`) instead of the `${{ ... }}` workflow interpolation. This prevents shell injection because environment variables are treated as simple strings by the shell, making it much harder for malicious content in the variable to break out of the intended usage.
Specifically:  
- Edit the step "Process meta.yaml file" at line 61–67,
- In `run:`, replace all workflow interpolations of …

Potential fix for code scanning alert no. 3: Code injection

---

script/get-ml-model-llama2/customize.py
script/get-ml-model-llama2/meta.yaml

support quantisation with v5.1 hashes + env variable fixes

---

automation/script/module.py

Add support for older mlcflow versions

---

script/app-mlperf-inference/customize.py

Changes to support the new compliance directory structure
