script/build-docker-image/customize.py
This commit helps to solve the following error:
```
Error: tag local/cm-script-get-ml-model-llama3--meta-llama/Llama-3.1-8B-Instruct:ubuntu-22.04-latest: invalid reference format: repository name must be lowercase
```
=> Generated docker image name - always lower case

script/push-mlperf-inference-results-to-github/run.sh
In reference to issue https://github.com/mlcommons/mlperf-automations/issues/239
=> Exit on error - git commit

script/app-mlperf-inference-mlcommons-python/customize.py
In reference to issue https://github.com/mlcommons/mlperf-automations/issues/248
=> Map rocm and gpu to cuda

automation/script/module.py
In reference to issue: https://github.com/mlcommons/mlperf-automations/issues/269
=> Fix duplication of automation object

.github/workflows/test-mlperf-inference-resnet50-closed-division.yml
=> Fix for ResNet50 Closed Division GitHub Action 

script/download-file/customize.py
=> Add option to skip the certificate check for rclone downloads

script/clean-nvidia-mlperf-inference-scratch-space/customize.py
Linked to PR: https://github.com/mlcommons/mlcflow/pull/145
=> Handle situation when cache is not present

script/get-preprocessed-dataset-openorca/customize.py
In reference to issue: https://github.com/mlcommons/mlperf-automations/issues/373
=> Fix import for OpenOrca

script/download-file/customize.py
Fixes #454  - Adds option to skip the s3 bucket check
=> Fixes #454

script/app-mlperf-inference-nvidia/meta.yaml
=> Fix for inheriting base variations - Nvidia

automation/script/lint.py, automation/script/module.py
=> Changes for supporting lint action

script/get-aocc/customize.py
=> Fix aocc version check regular expression

automation/script/doc.py
Description:
Adresses suggestion in PR #511
=> Return generated readme paths

script/build-dockerfile/dockerinfo.json
=> Install ca-certificates on launching container with MLC

script/app-mlperf-inference-mlcommons-python/customize.py, script/app-mlperf-inference-mlcommons-python/meta.yaml
In reference to commit: https://github.com/mlcommons/inference/commit/fa32df9a9a4be1eab86774e260a217360a1ff64d
=> Fix for whisper reference benchmark

script/push-mlperf-inference-results-to-github/customize.py
In reference to suggestion from PR. https://github.com/mlcommons/inference/pull/2280
=> Add logging in push results to GitHub 

script/app-mlperf-inference/meta.yaml, script/build-dockerfile/customize.py
=> Update mlperf inference docker base image

.github/workflows/build_wheel_off.yml, script/generate-mlperf-inference-submission/customize.py
In ref to: https://github.com/mlcommons/mlperf-automations/issues/558
=> Check required files before generating submission

script/run-docker-container/customize.py
=> Update customize.py | Fix docker error on gh actions

automation/script/doc.py, script/install-gcc-src/customize.py, script/install-gcc-src/meta.yaml, script/install-llvm-src/customize.py
=> Export src repo hash for install gcc,llvm

.github/workflows/run-tests-on-modified-meta.yml, .github/workflows/test-mlc-script-features.yml, .github/workflows/test-mlperf-automotive.yml, .github/workflows/test-mlperf-inference-bert-deepsparse-tf-onnxruntime-pytorch.yml, .github/workflows/test-mlperf-inference-resnet50.yml, .github/workflows/test-mlperf-inference-retinanet.yml, script/calibrate-model-for.qaic/customize.py
=> Merge from go

script/detect-cpu/run.bat
=> Replace wmic for Windows

automation/script/module.py, automation/utils.py
=> Support cache expiration

.github/workflows/build_wheel_off.yml, automation/script/docker.py, automation/script/docker_utils.py, automation/script/module.py, script/run-mlperf-inference-app/meta.yaml
=> Make --docker internal, and mlc docker script the default usage for docker runs

script/app-mlperf-inference-nvidia/customize.py, script/app-mlperf-inference-nvidia/meta.yaml, script/app-mlperf-inference/meta.yaml, script/build-mlperf-inference-server-nvidia/meta.yaml, script/get-mlperf-inference-nvidia-common-code/meta.yaml, script/get-mlperf-inference-results/meta.yaml, script/run-mlperf-inference-app/meta.yaml
Ref issue: https://github.com/mlcommons/mlperf-automations/issues/622
=> Base code changes for v5.1

script/install-llvm-src/meta.yaml
=> Include libunwind for install-llvm-src

script/download-file/customize.py
In reference to: https://github.com/mlcommons/mlperf-automations/issues/633
=> Support service account download in R2

script/get-ml-model-llama2/meta.yaml, script/run-mlperf-inference-app/meta.yaml
=> Add input mapping for downloading with service account credentials

.github/workflows/document-scripts.yml, script/get-generic-sys-util/meta.yaml, script/install-llvm-src/meta.yaml
=> Fix gfortran deps for flang cross-compilation

script/run-mlperf-inference-app/meta.yaml
Reference: https://github.com/mlcommons/inference_results_v5.1/tree/main/closed/NVIDIA#adding-a-new-or-custom-system
=> Map the system name env variable

script/app-mlperf-inference-nvidia/meta.yaml, script/app-mlperf-inference/meta.yaml, script/build-mlperf-inference-server-nvidia/meta.yaml
=> Prevent applying patch for nvmitten in v5.1

script/get-dataset-waymo/run.sh
Prevents the following warning:
```
image_4/1099138.jpg tar: image_4/1099138.jpg: Cannot change ownership to uid 1001, gid 1009: Operation not permitted
```
=> Skip ownership restore - Waymo dataset extraction

script/build-mlperf-inference-server-nvidia/customize.py
=> Fix #659, hpcx_paths usage in nvidia implementation

automation/script/docker_utils.py, script/app-mlperf-inference/meta.yaml, script/install-llvm-src/meta.yaml, script/run-docker-container/meta.yaml
=> Support docker privileged as input argument

script/get-preprocessed-dataset-nuscenes/customize.py, script/get-preprocessed-dataset-nuscenes/meta.yaml, script/get-preprocessed-dataset-nuscenes/run.sh
=> Support r2-downloader for nuscenes dataset download
